export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAILED';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const MARK_CATEGORY_TO_DELETE = 'MARK_CATEGORY_TO_DELETE';
export const DISCARD_CATEGORY_TO_DELETE = 'DISCARD_CATEGORY_TO_DELETE';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const CHANGE_CATEGORIES_ORDER = 'CHANGE_CATEGORIES_ORDER';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const CHANGE_PRODUCTS_FILTER = 'CHANGE_PRODUCTS_FILTER';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const MARK_PRODUCT_TO_DELETE = 'MARK_PRODUCT_TO_DELETE';
export const DISCARD_PRODUCT_TO_DELETE = 'DISCARD_PRODUCT_TO_DELETE';